AWSTemplateFormatVersion: "2010-09-09"

Resources:

  TBPSDBEC2forTomcat:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              git: []
    Properties: 
      InstanceType: t3.small
      ImageId: ami-a0cfeed8
      IamInstanceProfile: tbps-ec2-default
      InstanceInitiatedShutdownBehavior: stop
      KeyName: pstb-ec2-tomcat
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          DeviceIndex: 0
          GroupSet: 
            - "sg-ab83e4d7"
            - "sg-32810a4c"
          SubnetId: "subnet-32251954"
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - ' --stack '
            - !Ref 'AWS::StackName'
            - ' --resource TBPSDBEC2forTomcat '
            - ' --region '
            - !Ref 'AWS::Region'
            - ''
            - |
              # Execute Signal
            - '/opt/aws/bin/cfn-signal -e $? '
            - ' --stack '
            - !Ref 'AWS::StackName'
            - ' --resource TBPSDBEC2forTomcat '
            - ' --region '
            - !Ref 'AWS::Region'
            - ''
            - |
      Tags:
      - Key: "Name"
        Value: "tb-ps-ec2-default"
